import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const rootDir = join(__dirname, '..');
const packageJsonPath = join(rootDir, 'package.json');
const versionFilePath = join(rootDir, 'src', 'utils', 'version.ts');

// Read version from package.json
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
const version = packageJson.version;

// Ensure the utils directory exists
const utilsDir = dirname(versionFilePath);
if (!existsSync(utilsDir)) {
  mkdirSync(utilsDir, { recursive: true });
}

// Generate version.ts content
const content = `// Auto-generated by scripts/inject-version.js - DO NOT EDIT
export const APP_VERSION = '${version}';
`;

// Write the version file
writeFileSync(versionFilePath, content, 'utf-8');

console.log(`Version ${version} injected into ${versionFilePath}`);
